name: Integration tests with pytest (homework08)
on:
  push: 
    paths: 
      - 'homework08/**'

jobs:
  integration-tests-with-pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Start containers
      working-directory: ./homework08
      run: docker compose up --build -d

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip3 install pytest==9.0.* requests==2.*

    - name: Run pytest
      working-directory: ./homework08
      run: pytest

    - name: Stop images and clean up
      working-directory: ./homework08
      run: docker compose down